Update forecast-to-gcal.yml

diff --git a/.github/workflows/forecast-to-gcal.yml b/.github/workflows/forecast-to-gcal.yml
--- a/.github/workflows/forecast-to-gcal.yml
+++ b/.github/workflows/forecast-to-gcal.yml
@@ -29,4 +29,4 @@ jobs:
         env:
           GCAL_CALENDAR_ID: ${{ secrets.GCAL_CALENDAR_ID }}
           GCAL_SA_KEY_JSON: ${{ secrets.GCAL_SA_KEY_JSON }}
-        run: node gcal_push.js
+        run: node gcal_push.js || echo "FAILED"
